<a href="https://colab.research.google.com/github/akshayavb99/pytorch-examples/blob/main/zero-to-mastery-pytorch/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals
## Sample codes used in the material here - https://www.learnpytorch.io/00_pytorch_fundamentals/


### What is PyTorch?

PyTorch is an open source machine learning and deep learning framework based on the programming language Python, which allows us to design and run ML models. PyTorch allows us to work with pretrained models, and even define highly customizable deep learning models, where we can define the ML model layer by layer.

In [ ]:
#Importing relevant libraries
import torch
torch.__version__

'2.0.0+cu118'

### What are tensors?

Tensors are the basic data structures to represent data numerically. Tensors can be scalars (0 dimensions), vectors (1 dimension), matrices (2 dimensions), or even higher dimensions.  

### How can we tensors in PyTorch?

We can initialise tensors in PyTorch using the `torch.Tensor` class. Ther official documentation () offers much more information about the `torch.Tensor` class, like available datatypes, associated functions, valid mathematical operations etc.

In [ ]:
#Sample tensors
sample_scalar = torch.tensor(5)
sample_vector = torch.tensor([1,2])
sample_matrix = torch.tensor([[1,2,3],
                              [4,5,6],
                              [7,8,9]])
sample_tensor = torch.tensor([[[1,2,3],
                              [4,5,6],
                              [7,8,9]]])

In [ ]:
#Looking at some sample functions for tensors
def sampleFuncs(tensorVal=None):
  if tensorVal is None:
    tensorVal = torch.arange(0,100,10)
  
  print("Dimensions of the tensor: ", tensorVal.ndim)
  print("Shape of the tensor: ", tensorVal.shape)
  print("Datetype of tensor elements: ", tensorVal.dtype)
  print("Device on which tensor is stored (GPU - CUDA or CPU): ", tensorVal.device)
  print("")

In [ ]:
sampleFuncs(sample_scalar)
print()
sampleFuncs(sample_vector)
print()
sampleFuncs(sample_matrix)
print()
sampleFuncs(sample_tensor)
print()
sampleFuncs()

Dimensions of the tensor:  0
Shape of the tensor:  torch.Size([])
Datetype of tensor elements:  torch.int64
Device on which tensor is stored (GPU - CUDA or CPU):  cpu


Dimensions of the tensor:  1
Shape of the tensor:  torch.Size([2])
Datetype of tensor elements:  torch.int64
Device on which tensor is stored (GPU - CUDA or CPU):  cpu


Dimensions of the tensor:  2
Shape of the tensor:  torch.Size([3, 3])
Datetype of tensor elements:  torch.int64
Device on which tensor is stored (GPU - CUDA or CPU):  cpu


Dimensions of the tensor:  3
Shape of the tensor:  torch.Size([1, 3, 3])
Datetype of tensor elements:  torch.int64
Device on which tensor is stored (GPU - CUDA or CPU):  cpu


Dimensions of the tensor:  1
Shape of the tensor:  torch.Size([10])
Datetype of tensor elements:  torch.int64
Device on which tensor is stored (GPU - CUDA or CPU):  cpu



In [ ]:
def specialTensors():
  print("Random tensor: ", torch.rand(size=(3,4)))
  print()
  print("Zero tensor: ", torch.zeros(size=(3,4)))
  print()
  print("Ones tensor: ", torch.ones(size=(3,4)))
  print()
  print("Range of values: ", torch.arange(0,100,10))
  print()
  print("")

specialTensors()

Random tensor:  tensor([[0.0341, 0.0357, 0.6963, 0.8290],
        [0.6491, 0.4398, 0.0079, 0.2168],
        [0.6421, 0.9256, 0.8714, 0.3758]])

Zero tensor:  tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Ones tensor:  tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Range of values:  tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])




In [ ]:
def mathOperations(a,b):
  print("Sample tensors a,b: ", a,b)
  print("Adding 2 tensors: ", (a+b))
  print("Adding 2 tensors: ", torch.add(a,b))
  print("Subtracting 2 tensors: ", (a-b))
  print("Subtracting 2 tensors: ", torch.add(a,-b))
  print("Multiply tensors elementwise: ", (a*b))
  print("Multiply tensors elementwise: ", torch.multiply(a,b))
  print("Matrix multiplication: ", torch.matmul(a,b))
  print("Matrix multiplication: ", a @ b)
  print(" ")
  print("Sample tensor: ", a)
  print("Minimum of tensor: ", a.min())
  print("Minimum of tensor elements: ", torch.min(a))
  print("Maximum of tensor: ", a.max())
  print("Maximum of tensor elements: ", torch.max(a))
  print("Sum of tensor elements: ", a.sum())
  print("Sum of tensor elements: ", torch.sum(a))
  print("Mean of tensor elements: ", torch.mean(a.type(torch.float32)))
  print("Mean of tensor elements: ", a.type(torch.float32).mean())
  print()
  print("Sample tensor: ", a)
  print("Index of max value in tensor: ", a.argmax())
  print("Index of min value in tensor: ", a.argmin())
  print()

In [ ]:
mathOperations(torch.tensor([1,2,3]), torch.tensor([1,2,3]))

Sample tensors a,b:  tensor([1, 2, 3]) tensor([1, 2, 3])
Adding 2 tensors:  tensor([2, 4, 6])
Adding 2 tensors:  tensor([2, 4, 6])
Subtracting 2 tensors:  tensor([0, 0, 0])
Subtracting 2 tensors:  tensor([0, 0, 0])
Multiply tensors elementwise:  tensor([1, 4, 9])
Multiply tensors elementwise:  tensor([1, 4, 9])
Matrix multiplication:  tensor(14)
Matrix multiplication:  tensor(14)
 
Sample tensor:  tensor([1, 2, 3])
Minimum of tensor:  tensor(1)
Minimum of tensor elements:  tensor(1)
Maximum of tensor:  tensor(3)
Maximum of tensor elements:  tensor(3)
Sum of tensor elements:  tensor(6)
Sum of tensor elements:  tensor(6)
Mean of tensor elements:  tensor(2.)
Mean of tensor elements:  tensor(2.)

Sample tensor:  tensor([1, 2, 3])
Index of max value in tensor:  tensor(2)
Index of min value in tensor:  tensor(0)



In [ ]:
def testStacking():

  x = torch.tensor([[1,2],
                  [3,4],
                  [5,6]])
  x_stacked = torch.stack([x+5,x+10,x+15,x+20], dim=0)
  print("Stacking along dim=0: \n", x_stacked)
  print()
  x_stacked = torch.stack([x+5,x+10,x+15,x+20], dim=1)
  print("Stacking along dim=1: \n", x_stacked)
  print()
  x_stacked = torch.stack([x,x+5,x+10,x+15], dim=2)
  print("Stacking along dim=2: \n", x_stacked)
  print()

In [ ]:
testStacking()

Stacking along dim=0: 
 tensor([[[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[11, 12],
         [13, 14],
         [15, 16]],

        [[16, 17],
         [18, 19],
         [20, 21]],

        [[21, 22],
         [23, 24],
         [25, 26]]])

Stacking along dim=1: 
 tensor([[[ 6,  7],
         [11, 12],
         [16, 17],
         [21, 22]],

        [[ 8,  9],
         [13, 14],
         [18, 19],
         [23, 24]],

        [[10, 11],
         [15, 16],
         [20, 21],
         [25, 26]]])

Stacking along dim=2: 
 tensor([[[ 1,  6, 11, 16],
         [ 2,  7, 12, 17]],

        [[ 3,  8, 13, 18],
         [ 4,  9, 14, 19]],

        [[ 5, 10, 15, 20],
         [ 6, 11, 16, 21]]])



### Additional source to understand how torch.stack works similar to numpy.hstack and numpy.vstack - https://stackoverflow.com/questions/69220221/use-of-torch-stack