<a href="https://colab.research.google.com/github/akshayavb99/pytorch-examples/blob/main/zero-to-mastery-pytorch/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals
## Sample codes used in the material here - https://www.learnpytorch.io/00_pytorch_fundamentals/


### What is PyTorch?

PyTorch is an open source machine learning and deep learning framework based on the programming language Python, which allows us to design and run ML models. PyTorch allows us to work with pretrained models, and even define highly customizable deep learning models, where we can define the ML model layer by layer.

In [25]:
#Importing relevant libraries
import torch
torch.__version__

'2.0.0+cu118'

### What are tensors?

Tensors are the basic data structures to represent data numerically. Tensors can be scalars (0 dimensions), vectors (1 dimension), matrices (2 dimensions), or even higher dimensions.  

### How can we tensors in PyTorch?

We can initialise tensors in PyTorch using the `torch.Tensor` class. Ther official documentation () offers much more information about the `torch.Tensor` class, like available datatypes, associated functions, valid mathematical operations etc.

In [26]:
#Sample tensors
sample_scalar = torch.tensor(5)
sample_vector = torch.tensor([1,2])
sample_matrix = torch.tensor([[1,2,3],
                              [4,5,6],
                              [7,8,9]])
sample_tensor = torch.tensor([[[1,2,3],
                              [4,5,6],
                              [7,8,9]]])

In [27]:
#Looking at some sample functions for tensors
def sampleFuncs(tensorVal=None):
  if tensorVal is None:
    tensorVal = torch.arange(0,100,10)
  
  print("Dimensions of the tensor: ", tensorVal.ndim)
  print("Shape of the tensor: ", tensorVal.shape)
  print("Datetype of tensor elements: ", tensorVal.dtype)
  print("Device on which tensor is stored (GPU - CUDA or CPU): ", tensorVal.device)
  print("")

In [28]:
sampleFuncs(sample_scalar)
print()
sampleFuncs(sample_vector)
print()
sampleFuncs(sample_matrix)
print()
sampleFuncs(sample_tensor)
print()
sampleFuncs()

Dimensions of the tensor:  0
Shape of the tensor:  torch.Size([])
Datetype of tensor elements:  torch.int64
Device on which tensor is stored (GPU - CUDA or CPU):  cpu


Dimensions of the tensor:  1
Shape of the tensor:  torch.Size([2])
Datetype of tensor elements:  torch.int64
Device on which tensor is stored (GPU - CUDA or CPU):  cpu


Dimensions of the tensor:  2
Shape of the tensor:  torch.Size([3, 3])
Datetype of tensor elements:  torch.int64
Device on which tensor is stored (GPU - CUDA or CPU):  cpu


Dimensions of the tensor:  3
Shape of the tensor:  torch.Size([1, 3, 3])
Datetype of tensor elements:  torch.int64
Device on which tensor is stored (GPU - CUDA or CPU):  cpu


Dimensions of the tensor:  1
Shape of the tensor:  torch.Size([10])
Datetype of tensor elements:  torch.int64
Device on which tensor is stored (GPU - CUDA or CPU):  cpu



In [29]:
def specialTensors():
  print("Random tensor: ", torch.rand(size=(3,4)))
  print()
  print("Zero tensor: ", torch.zeros(size=(3,4)))
  print()
  print("Ones tensor: ", torch.ones(size=(3,4)))
  print()
  print("Range of values: ", torch.arange(0,100,10))
  print()
  print("")

specialTensors()

Random tensor:  tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

Zero tensor:  tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Ones tensor:  tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Range of values:  tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])




In [30]:
def mathOperations(a,b):
  print("Sample tensors a,b: ", a,b)
  print("Adding 2 tensors: ", (a+b))
  print("Adding 2 tensors: ", torch.add(a,b))
  print("Subtracting 2 tensors: ", (a-b))
  print("Subtracting 2 tensors: ", torch.add(a,-b))
  print("Multiply tensors elementwise: ", (a*b))
  print("Multiply tensors elementwise: ", torch.multiply(a,b))
  print("Matrix multiplication: ", torch.matmul(a,b))
  print("Matrix multiplication: ", a @ b)
  print(" ")
  print("Sample tensor: ", a)
  print("Minimum of tensor: ", a.min())
  print("Minimum of tensor elements: ", torch.min(a))
  print("Maximum of tensor: ", a.max())
  print("Maximum of tensor elements: ", torch.max(a))
  print("Sum of tensor elements: ", a.sum())
  print("Sum of tensor elements: ", torch.sum(a))
  print("Mean of tensor elements: ", torch.mean(a.type(torch.float32)))
  print("Mean of tensor elements: ", a.type(torch.float32).mean())
  print()
  print("Sample tensor: ", a)
  print("Index of max value in tensor: ", a.argmax())
  print("Index of min value in tensor: ", a.argmin())
  print()

In [31]:
mathOperations(torch.tensor([1,2,3]), torch.tensor([1,2,3]))

Sample tensors a,b:  tensor([1, 2, 3]) tensor([1, 2, 3])
Adding 2 tensors:  tensor([2, 4, 6])
Adding 2 tensors:  tensor([2, 4, 6])
Subtracting 2 tensors:  tensor([0, 0, 0])
Subtracting 2 tensors:  tensor([0, 0, 0])
Multiply tensors elementwise:  tensor([1, 4, 9])
Multiply tensors elementwise:  tensor([1, 4, 9])
Matrix multiplication:  tensor(14)
Matrix multiplication:  tensor(14)
 
Sample tensor:  tensor([1, 2, 3])
Minimum of tensor:  tensor(1)
Minimum of tensor elements:  tensor(1)
Maximum of tensor:  tensor(3)
Maximum of tensor elements:  tensor(3)
Sum of tensor elements:  tensor(6)
Sum of tensor elements:  tensor(6)
Mean of tensor elements:  tensor(2.)
Mean of tensor elements:  tensor(2.)

Sample tensor:  tensor([1, 2, 3])
Index of max value in tensor:  tensor(2)
Index of min value in tensor:  tensor(0)



In [32]:
def testStacking():

  x = torch.tensor([[1,2],
                  [3,4],
                  [5,6]])
  x_stacked = torch.stack([x+5,x+10,x+15,x+20], dim=0)
  print("Stacking along dim=0: \n", x_stacked)
  print()
  x_stacked = torch.stack([x+5,x+10,x+15,x+20], dim=1)
  print("Stacking along dim=1: \n", x_stacked)
  print()
  x_stacked = torch.stack([x,x+5,x+10,x+15], dim=2)
  print("Stacking along dim=2: \n", x_stacked)
  print()

In [33]:
testStacking()

Stacking along dim=0: 
 tensor([[[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[11, 12],
         [13, 14],
         [15, 16]],

        [[16, 17],
         [18, 19],
         [20, 21]],

        [[21, 22],
         [23, 24],
         [25, 26]]])

Stacking along dim=1: 
 tensor([[[ 6,  7],
         [11, 12],
         [16, 17],
         [21, 22]],

        [[ 8,  9],
         [13, 14],
         [18, 19],
         [23, 24]],

        [[10, 11],
         [15, 16],
         [20, 21],
         [25, 26]]])

Stacking along dim=2: 
 tensor([[[ 1,  6, 11, 16],
         [ 2,  7, 12, 17]],

        [[ 3,  8, 13, 18],
         [ 4,  9, 14, 19]],

        [[ 5, 10, 15, 20],
         [ 6, 11, 16, 21]]])



### Additional source to understand how torch.stack works similar to numpy.hstack and numpy.vstack - https://stackoverflow.com/questions/69220221/use-of-torch-stack

In [34]:
#Changing tensor across different dimensions

def changeDims(x=None):
  if x is None:
    x = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
  print("Original tensor: \n", x)
  print()

  print("Indexing tensors\n")
  print(x[0])
  print(x[0][0])
  print(x[0][0][0])
  print()

  print("Reshape original tensor to desired shape\n")
  print("Reshaped tensor\n")
  x = torch.reshape(x,(1,1,9))
  print(x)
  #Reverting to original shape
  x = torch.reshape(x,(1,3,3))
  print()

  print("Changing the shape of the view of the tensor\n")
  print("View of tensor with new shape\n")
  print(x.view((1,1,9)))
  print()

  print("Removing dimensions (equal to 1) from a tensor\n")
  print(x.shape)
  print(x.reshape((1,1,9)).shape)
  print(x.reshape((1,1,9)).squeeze().shape)
  print()

  print("Adding dimensions (equal to 1) to a tensor\n")
  print(x.shape)
  print(x.reshape((1,1,9)).shape)
  print(x.reshape((1,1,9)).unsqueeze(dim=0).shape)
  print(x.reshape((1,1,9)).unsqueeze(dim=1).shape)
  print(x.reshape((1,1,9)).unsqueeze(dim=2).shape)
  print(x.reshape((1,1,9)).unsqueeze(dim=3).shape)
  print()

  print("Permutating elements of tensor\n")
  y = x.clone()
  print(y.permute(2, 0, 1)) # shifts axis 0->1, 1->2, 2->0
  print()

In [35]:
changeDims()

Original tensor: 
 tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

Indexing tensors

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)

Reshape original tensor to desired shape

Reshaped tensor

tensor([[[1, 2, 3, 4, 5, 6, 7, 8, 9]]])

Changing the shape of the view of the tensor

View of tensor with new shape

tensor([[[1, 2, 3, 4, 5, 6, 7, 8, 9]]])

Removing dimensions (equal to 1) from a tensor

torch.Size([1, 3, 3])
torch.Size([1, 1, 9])
torch.Size([9])

Adding dimensions (equal to 1) to a tensor

torch.Size([1, 3, 3])
torch.Size([1, 1, 9])
torch.Size([1, 1, 1, 9])
torch.Size([1, 1, 1, 9])
torch.Size([1, 1, 1, 9])
torch.Size([1, 1, 9, 1])

Permutating elements of tensor

tensor([[[1, 4, 7]],

        [[2, 5, 8]],

        [[3, 6, 9]]])



### Some additional information about torch.view and torch.reshape - https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch

In [36]:
def testingGPUConnect():
  print(torch.cuda.is_available())
  gpuDevice = 'cuda' if torch.cuda.is_available() else 'cpu'
  print(gpuDevice)
  print()

  #Counting number of GPUs accessible
  print("Number of available GPUs = ", torch.cuda.device_count())

In [37]:
testingGPUConnect()

True
cuda

Number of available GPUs =  1


In [38]:
def tensorsOnGPU():
  tensor = torch.tensor([1,2,3])
  print(tensor, tensor.device)

  gpuDevice = 'cuda' if torch.cuda.is_available() else 'cpu'
  tensor = tensor.to(gpuDevice)
  print(tensor, tensor.device)

  tensor = tensor.cpu()
  print(tensor, tensor.device)

In [39]:
tensorsOnGPU()

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cuda:0
tensor([1, 2, 3]) cpu


### Exercise Solutions

#### Exercise template: https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb



1. Documentation reading on <br>
  a. torch.Tensor <br>
  b. torch.cuda


2. Create a random tensor with shape (7,7)

In [40]:
second = torch.rand((7,7))
second

tensor([[0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062, 0.9516],
        [0.0753, 0.8860, 0.5832, 0.3376, 0.8090, 0.5779, 0.9040],
        [0.5547, 0.3423, 0.6343, 0.3644, 0.7104, 0.9464, 0.7890],
        [0.2814, 0.7886, 0.5895, 0.7539, 0.1952, 0.0050, 0.3068],
        [0.1165, 0.9103, 0.6440, 0.7071, 0.6581, 0.4913, 0.8913],
        [0.1447, 0.5315, 0.1587, 0.6542, 0.3278, 0.6532, 0.3958],
        [0.9147, 0.2036, 0.2018, 0.2018, 0.9497, 0.6666, 0.9811]])

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)

In [41]:
third = torch.rand((1,7))
multTensor = torch.matmul(second,third.T)
multTensor

tensor([[1.3417],
        [1.9172],
        [2.0426],
        [0.6368],
        [1.8116],
        [1.1753],
        [2.1538]])

4. Set the random seed to 0 and do 2 & 3 over again.

In [42]:
torch.manual_seed(0)
third = torch.rand((1,7))
multTensor = torch.matmul(second,third.T)
multTensor

tensor([[0.9558],
        [1.8724],
        [1.8477],
        [1.1108],
        [1.8581],
        [1.2895],
        [1.8504]])

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed)

In [46]:
torch.manual_seed(42)
if torch.cuda.is_available():
  torch.cuda.manual_seed(1234)
  device = 'cuda'
else:
  device = 'cpu'
tensor_1 = torch.rand((2,3)).to(device)
tensor_2 = torch.rand((2,3)).to(device)
print(tensor_1)
print(tensor_2)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]], device='cuda:0')
tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]], device='cuda:0')


7. Perform a matrix multiplication on the tensors you created in 6

In [48]:
seven = torch.matmul(tensor_1,tensor_2.T)
seven, seven.shape

(tensor([[1.3127, 1.1999],
         [1.1213, 0.8494]], device='cuda:0'),
 torch.Size([2, 2]))

8. Find the maximum and minimum values of the output of 7.

In [49]:
seven.max(), seven.min()

(tensor(1.3127, device='cuda:0'), tensor(0.8494, device='cuda:0'))

9. Find the maximum and minimum index values of the output of 7.

In [50]:
torch.argmax(seven), torch.argmin(seven)

(tensor(0, device='cuda:0'), tensor(3, device='cuda:0'))

10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [52]:
torch.manual_seed(7)
tensor_1 = torch.rand((1,1,1,10))
tensor_2 = torch.squeeze(torch.squeeze(torch.squeeze(tensor_1)))
print(tensor_1, tensor_1.shape)
print()
print(tensor_2, tensor_2.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
